columns:
  categorical:
  - Targ
  - disease_site
  - regimen
  - intent
  - gender
  continuous:
  - glucose
  - neutrophil
  - lactate_dehydrogenase
  - hemoglobin
  - mean_platelet_volume
  - lymphocyte
  - total_bilirubin
  - mean_corpuscular_hemoglobin
  - creatinine
  - red_blood_cell
  - body_surface_area
  - platelet
  - alanine_aminotransferase
  - mean_corpuscular_hemoglobin_concentration
  - weight
  - red_cell_distribution_width
  - aspartate_aminotransferase
  - magnesium
  - monocyte
  - alkaline_phosphatase
  - hematocrit
  - white_blood_cell
  - mean_corpuscular_volume
  - eosinophil
  - phosphate
  - patient_ecog
  - potassium
  - bicarbonate
  - esas_pain
  - esas_drowsiness
  - esas_well_being
  - esas_nausea
  - albumin
  - esas_tiredness
  - esas_depression
  - chloride
  - age
  - esas_anxiety
  - height
  - sodium
  - esas_shortness_of_breath
  - cycle_number
  - line_of_therapy
  - esas_appetite
  date: []
  other: []
mapping:
  Targ:
    'False': 'False'
    'True': 'True'
  disease_site:
    C05: Other
    C06: Other
    C09: Other
    C10: Other
    C11: Other
    C15: C15
    C16: C16
    C17: Other
    C18: C18
    C19: C19
    C20: C20
    C21: C21
    C22: C22
    C23: Other
    C24: C24
    C25: C25
    C34: Other
  gender:
    Female: Female
    Male: Male
  intent:
    ADJUVANT: ADJUVANT
    CURATIVE: CURATIVE
    NEOADJUVANT: NEOADJUVANT
    PALLIATIVE: PALLIATIVE
  regimen:
    GI-CISPCAPE+TRAS(LOAD): Other
    GI-CISPCAPE+TRAS(MAIN): GI-CISPCAPE+TRAS(MAIN)
    GI-CISPFU ANAL: Other
    GI-CISPFU ESOPHAGEAL: Other
    GI-ECF: GI-ECF
    GI-ECX: GI-ECX
    GI-FLOT (GASTRIC): Other
    GI-FOLFIRI: GI-FOLFIRI
    GI-FOLFIRI+BEVACIZUMAB: GI-FOLFIRI+BEVACIZUMAB
    GI-FOLFIRI+PANITUMUMAB: Other
    GI-FOLFIRINOX: GI-FOLFIRINOX
    GI-FOLFOX (GASTRIC): GI-FOLFOX (GASTRIC)
    GI-FOLFOX+BEVACIZUMAB: GI-FOLFOX+BEVACIZUMAB
    GI-FOLFOX-6 MOD: GI-FOLFOX-6 MOD
    GI-FU CIV + RT: Other
    GI-FU/FA/CISP BILIARY: Other
    GI-FUFA C1,4,5 GASTRIC: GI-FUFA C1,4,5 GASTRIC
    GI-FUFA C2 (GASTRIC): Other
    GI-FUFA C3 (GASTRIC): Other
    GI-FUFA WEEKLY: Other
    GI-GEM 40MG/M2 2X/WK: GI-GEM 40MG/M2 2X/WK
    GI-GEM 7-WEEKLY: Other
    GI-GEM D1,8: GI-GEM D1,8
    GI-GEM D1,8,15: GI-GEM D1,8,15
    GI-GEM+ABRAXANE: GI-GEM+ABRAXANE
    GI-GEMCAP: Other
    GI-GEMCISP (BILIARY): GI-GEMCISP (BILIARY)
    GI-GEMCISP (PANCREAS): GI-GEMCISP (PANCREAS)
    GI-GEMFU (BILIARY): Other
    GI-IRINO 4-WEEKLY: Other
    GI-IRINO Q3W: Other
    GI-MITOFU: GI-MITOFU
    GI-PACLI WEEKLY: Other
    GI-PACLI/CARBO WEEKX5: GI-PACLI/CARBO WEEKX5
    GI-PANITUMUMAB: GI-PANITUMUMAB
    GI-RAMUC(CCO)+PACL(W): Other
    GI-RAMUCIRUMAB+PACLI: GI-RAMUCIRUMAB+PACLI
    GI-XELOX: Other
missingness_strategy:
  categorical:
    Targ: Unknown
    disease_site: Unknown
    gender: Unknown
    intent: Unknown
    regimen: Unknown
  continuous:
    age: median
    alanine_aminotransferase: median
    albumin: median
    alkaline_phosphatase: median
    aspartate_aminotransferase: median
    bicarbonate: median
    body_surface_area: median
    chloride: median
    creatinine: median
    cycle_number: median
    eosinophil: median
    esas_anxiety: median
    esas_appetite: median
    esas_depression: median
    esas_drowsiness: median
    esas_nausea: median
    esas_pain: median
    esas_shortness_of_breath: median
    esas_tiredness: median
    esas_well_being: median
    glucose: median
    height: median
    hematocrit: median
    hemoglobin: median
    lactate_dehydrogenase: median
    line_of_therapy: median
    lymphocyte: median
    magnesium: median
    mean_corpuscular_hemoglobin: median
    mean_corpuscular_hemoglobin_concentration: median
    mean_corpuscular_volume: median
    mean_platelet_volume: median
    monocyte: median
    mrn: median
    neutrophil: median
    patient_ecog: median
    phosphate: median
    platelet: median
    potassium: median
    red_blood_cell: median
    red_cell_distribution_width: median
    sodium: median
    total_bilirubin: median
    weight: median
    white_blood_cell: median
