[project]
name = "jarvais"
channels = ["conda-forge", "pytorch"]
platforms = ["linux-64", "win-64", "osx-64"]

[tasks]
example = "jupyter lab"

[dependencies]
python = ">=3.10"

[pypi-dependencies]
jarvais = { path = ".", editable = true }


[environments]
dev = { features = ["test", "style", "dev"], solve-group = "default" }
publish = { features = ["build", "release"], solve-group = "default" }
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]

############################################## dev ###############################################

[feature.dev.pypi-dependencies]
jarvais = { path = ".", editable = true}
mkdocs-material = ">=9.5.49,<10" 
mkdocs-jupyter = ">=0.25.1,<0.26" 
mkdocs-pdf = ">=0.1.2,<0.2"
mkdocstrings = { version = ">=0.27.0, <0.28", extras = ["python"] }

[feature.dev.dependencies]
jupyterlab = ">=4.2.5,<5"
mkdocs = ">=1.6.1,<2"


############################################## python ###############################################

[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"

############################################## TEST ################################################

[feature.test.dependencies]
pytest = "*"

[feature.test.tasks.test]
cmd = [
  "pytest",
  "--verbose",
  "-s",
]
inputs = ["src", "tests"]
description = "Run pytest"

############################################## STYLE ###############################################
# See configs/ruff.toml for the configuration
[feature.style.dependencies]
ruff = ">=0.4.4"
pre-commit = ">=3.7.1,<3.8"

[feature.style.tasks]
[feature.style.tasks.lint]
cmd = "ruff check  --config=configs/ruff.toml"
inputs = ["src", "configs/ruff.toml"]
description = "Run ruff linter"

[feature.style.tasks.format]
cmd = "ruff format --config=configs/ruff.toml"
inputs = ["src", "configs/ruff.toml"]
description = "Run ruff formatter, use `--diff` to see changes only"

#################################### RELEASE & BUILD ###############################################

[feature.release.dependencies]
python-semantic-release = "*"

[feature.release.tasks]
semver = 'echo "Next Version is: $(semantic-release version --print)"'
release = "semantic-release version"

[feature.build.dependencies]
hatch = "*"

[feature.build.tasks]
# Builds the package
build = { cmd = [
  "hatch",
  "build",
  "--clean",
], inputs = [
  "src",
  "pyproject.toml",
], outputs = [
  "dist/*",
], description = "Build the package" }

# Publishes the package to the main PYPI repository, depends on the build task
publish-pypi = { cmd = [
  "hatch",
  "publish",
  "--yes",
  "--repo",
  "main",
], inputs = [
  "dist/*",
], depends-on = [
  "build",
], description = "Publish to main PyPI" }
