columns:
  categorical:
  - OAR
  - patient
  - Targ
  continuous:
  - SurfDist
  - 95HD
  - FNPL
  - VolDice
  - FNV
  - APL
  - JaccardIndex
  - MAR
  date: []
  other: []
mapping:
  OAR:
    Acoustic_L: Acoustic_L
    Acoustic_R: Acoustic_R
    BrachialPlex_L: BrachialPlex_L
    BrachialPlex_R: BrachialPlex_R
    Brainstem: Brainstem
    Esophagus: Esophagus
    Eye_L: Eye_L
    Eye_R: Eye_R
    Larynx: Larynx
    Lens_L: Lens_L
    Lens_R: Lens_R
    Lips: Lips
    Mandible_Bone: Mandible_Bone
    Nrv_Optic_L: Nrv_Optic_L
    Nrv_Optic_R: Nrv_Optic_R
    OpticChiasm: OpticChiasm
    Parotid_L: Parotid_L
    Parotid_R: Parotid_R
    SpinalCord: SpinalCord
  Targ:
    'False': 'False'
    'True': 'True'
  patient:
    RADCURE-0025: RADCURE-0025
    RADCURE-0031: RADCURE-0031
    RADCURE-0053: RADCURE-0053
    RADCURE-0161: RADCURE-0161
    RADCURE-0210: RADCURE-0210
    RADCURE-0223: RADCURE-0223
    RADCURE-0246: RADCURE-0246
    RADCURE-0407: RADCURE-0407
    RADCURE-0550: RADCURE-0550
    RADCURE-0553: RADCURE-0553
    RADCURE-0744: RADCURE-0744
    RADCURE-0783: RADCURE-0783
    RADCURE-0787: RADCURE-0787
    RADCURE-0851: RADCURE-0851
    RADCURE-0983: RADCURE-0983
    RADCURE-1035: RADCURE-1035
    RADCURE-1061: RADCURE-1061
    RADCURE-1187: RADCURE-1187
    RADCURE-1939: RADCURE-1939
    RADCURE-2141: RADCURE-2141
    RADCURE-2299: RADCURE-2299
    RADCURE-2304: RADCURE-2304
    RADCURE-2421: RADCURE-2421
    RADCURE-2460: RADCURE-2460
    RADCURE-2576: RADCURE-2576
    RADCURE-2722: RADCURE-2722
    RADCURE-2908: RADCURE-2908
    RADCURE-2910: RADCURE-2910
    RADCURE-2939: RADCURE-2939
    RADCURE-2976: Other
    RADCURE-2981: RADCURE-2981
    RADCURE-3096: RADCURE-3096
    RADCURE-3109: RADCURE-3109
    RADCURE-3123: RADCURE-3123
    RADCURE-3263: RADCURE-3263
    RADCURE-3330: RADCURE-3330
    RADCURE-3385: RADCURE-3385
    RADCURE-3403: RADCURE-3403
    RADCURE-3410: RADCURE-3410
    RADCURE-3425: Other
    RADCURE-3506: RADCURE-3506
    RADCURE-3521: Other
    RADCURE-3556: RADCURE-3556
    RADCURE-3571: RADCURE-3571
    RADCURE-3588: RADCURE-3588
    RADCURE-3622: RADCURE-3622
    RADCURE-3625: RADCURE-3625
    RADCURE-3653: RADCURE-3653
    RADCURE-3658: RADCURE-3658
    RADCURE-3663: RADCURE-3663
    RADCURE-3689: Other
    RADCURE-3698: Other
    RADCURE-3714: RADCURE-3714
    RADCURE-3739: RADCURE-3739
    RADCURE-3753: RADCURE-3753
    RADCURE-3812: RADCURE-3812
    RADCURE-3876: RADCURE-3876
    RADCURE-3929: Other
missingness_strategy:
  categorical:
    OAR: Unknown
    Targ: Unknown
    patient: Unknown
  continuous:
    95HD: median
    APL: median
    FNPL: median
    FNV: median
    JaccardIndex: median
    MAR: median
    SurfDist: median
    VolDice: median
