columns:
  categorical:
  - T Stage
  - Disease Site
  - N Stage
  - Sex
  - Stage
  - event
  - Chemotherapy
  - EGFRI
  - HPV Combined
  continuous:
  - age at dx
  - time
  - Dose
  date: []
  other: []
mapping:
  Chemotherapy:
    '0': '0'
    '1': '1'
  Disease Site:
    esophagus: Other
    hypopharynx: hypopharynx
    larynx: larynx
    lip & oral cavity: lip & oral cavity
    nasal cavity: nasal cavity
    nasopharynx: nasopharynx
    oropharynx: oropharynx
    paranasal sinus: paranasal sinus
    salivary glands: Other
  Dose:
    '50.0': Other
    '50.8': Other
    '51.0': '51.0'
    '53.55': Other
    '55.0': Other
    '59.4': Other
    '60.0': '60.0'
    '64.0': '64.0'
    '66.0': '66.0'
    '69.96': Other
    '70.0': '70.0'
  EGFRI:
    '0': '0'
    '1': '1'
  HPV Combined:
    '0.0': '0.0'
    '1.0': '1.0'
    nan: nan
  N Stage:
    N0: N0
    N1: N1
    N2: N2
    N2a: N2a
    N2b: N2b
    N2c: N2c
    N3: N3
    N3a: Other
    N3b: N3b
    NX: Other
  Sex:
    Female: Female
    Male: Male
  Stage:
    '0': '0'
    I: I
    II: II
    IIA: Other
    III: III
    IIIA: Other
    IIIC: Other
    IV: Other
    IVA: IVA
    IVB: IVB
    nan: nan
  T Stage:
    T1: T1
    T1a: T1a
    T1b: T1b
    T2: T2
    T2 (2): Other
    T3: T3
    T3 (2): Other
    T4: T4
    T4a: T4a
    T4b: T4b
    TX: Other
    Tis: Tis
  event:
    '0': '0'
    '1': '1'
missingness_strategy:
  categorical:
    Chemotherapy: Unknown
    Disease Site: Unknown
    Dose: Unknown
    EGFRI: Unknown
    HPV Combined: Unknown
    N Stage: Unknown
    Sex: Unknown
    Stage: Unknown
    T Stage: Unknown
    event: Unknown
  continuous:
    age at dx: median
    time: median
