columns:
  categorical:
  - gender
  - target_ED_visit
  - intent
  - regimen
  - disease_site
  continuous:
  - glucose
  - neutrophil
  - aspartate_aminotransferase
  - hematocrit
  - weight
  - white_blood_cell
  - red_blood_cell
  - mean_corpuscular_volume
  - body_surface_area
  - red_cell_distribution_width
  - platelet
  - mean_corpuscular_hemoglobin
  - alanine_aminotransferase
  - days_since_prev_ED_visit
  - lactate_dehydrogenase
  - lymphocyte
  - alkaline_phosphatase
  - esas_nausea
  - age
  - hemoglobin
  - patient_ecog
  - creatinine
  - chloride
  - phosphate
  - esas_anxiety
  - sodium
  - potassium
  - esas_depression
  - total_bilirubin
  - esas_well_being
  - bicarbonate
  - eosinophil
  - height
  - mean_corpuscular_hemoglobin_concentration
  - esas_pain
  - num_prior_ED_visits_within_5_years
  - albumin
  - esas_drowsiness
  - monocyte
  - cycle_number
  - esas_shortness_of_breath
  - esas_tiredness
  - mean_platelet_volume
  - esas_appetite
  - magnesium
  date:
  - treatment_date
  - first_treatment_date
  other: []
mapping:
  target_ED_visit:
    'False': 'False'
    'True': 'True'
missingness_strategy:
  categorical:
    age: Unknown
    albumin: Unknown
    bicarbonate: Unknown
    chloride: Unknown
    creatinine: Unknown
    cycle_number: Unknown
    disease_site: Unknown
    eosinophil: Unknown
    esas_anxiety: Unknown
    esas_appetite: Unknown
    esas_depression: Unknown
    esas_drowsiness: Unknown
    esas_nausea: Unknown
    esas_pain: Unknown
    esas_shortness_of_breath: Unknown
    esas_tiredness: Unknown
    esas_well_being: Unknown
    gender: Unknown
    height: Unknown
    hemoglobin: Unknown
    intent: Unknown
    magnesium: Unknown
    mean_corpuscular_hemoglobin_concentration: Unknown
    mean_platelet_volume: Unknown
    monocyte: Unknown
    num_prior_ED_visits_within_5_years: Unknown
    patient_ecog: Unknown
    phosphate: Unknown
    potassium: Unknown
    regimen: Unknown
    sodium: Unknown
    target_ED_visit: Unknown
    total_bilirubin: Unknown
  continuous:
    alanine_aminotransferase: median
    alkaline_phosphatase: median
    aspartate_aminotransferase: median
    body_surface_area: median
    days_since_prev_ED_visit: median
    glucose: median
    hematocrit: median
    lactate_dehydrogenase: median
    lymphocyte: median
    mean_corpuscular_hemoglobin: median
    mean_corpuscular_volume: median
    neutrophil: median
    platelet: median
    red_blood_cell: median
    red_cell_distribution_width: median
    weight: median
    white_blood_cell: median
